---

# Перечисляем хосты на которые развернем с помощью ролей нужный софт

- hosts: vmdb
  roles:

# ставим ролью БД плюс к ней роли для установки экспортеров сбора метрик

    - { role: postgresql }
    - { role: node_exporter }
    - { role: postgres_exporter }
  vars:

# Передали версию СУБД, настройки самой СУБД, имя создаваемой БД и пользователя для нее

    postgresql_version: 14
    postgresql_install_from_pgdg: true
    postgresql_options:
      - {key: listen_addresses, value: "'*'"}
      - {key: max_connections, value: 200}
      - {key: shared_buffers, value: 1GB}
    postgresql_databases:
      - name: prom
    postgresql_users:
      - name: prom
        password: "{{ vault_postgresql_password_prom }}"
        db: prom
# Передаем файл с паролем зашифрованным ansible-vault 

  vars_files:
    - roles/postgresql/vars/postgres_pass.yml

- hosts: vmprtm

# На хост ставим Prometheus и к нему экспортер 

  roles:
    - { role: prometheus}
    - { role: node_exporter }
  vars:

# Здесь настраиваем хосты с которых собираем метрики и их эндпоинты

    prometheus_targets:
      node:
      - targets:
        - localhost:9100
        - node.demo.do.prometheus.io
        - 172.16.0.100:9100
        - 172.16.0.100:9187
